Use ElQuiosco

INSERT INTO PROVINCIAS(DESCRIPCION, ACTIVO) VALUES
('San José', 1),
('Cartago', 1),
('Heredia', 1),
('Limon', 1),
('Guanacaste', 1),
('Puntarenas', 1),
('Alajuela', 1);

-- San José
INSERT INTO CANTON (DESCRIPCION, ACTIVO, ID_PROVINCIA) VALUES
('San José', 1, 1),
('Escazú', 1, 1),
('Desamparados', 1, 1),
('Puriscal', 1, 1),
('Tarrazú', 1, 1),
('Aserrí', 1, 1),
('Mora', 1, 1),
('Goicoechea', 1, 1),
('Santa Ana', 1, 1),
('Alajuelita', 1, 1),
('Vázquez de Coronado', 1, 1),
('Acosta', 1, 1),
('Tibás', 1, 1),
('Moravia', 1, 1),
('Montes de Oca', 1, 1),
('Turrubares', 1, 1),
('Dota', 1, 1),
('Curridabat', 1, 1),
('Pérez Zeledón', 1, 1),
('León Cortés Castro', 1, 1);

-- San José
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Carmen', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San José' AND ID_PROVINCIA=1)),
('Merced', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San José' AND ID_PROVINCIA=1)),
('Hospital', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San José' AND ID_PROVINCIA=1)),
('Catedral', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San José' AND ID_PROVINCIA=1));

-- Escazú
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Escazú', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Escazú' AND ID_PROVINCIA=1)),
('San Rafael', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Escazú' AND ID_PROVINCIA=1)),
('San Antonio', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Escazú' AND ID_PROVINCIA=1));

-- Desamparados
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Desamparados', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Desamparados' AND ID_PROVINCIA=1)),
('San Miguel', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Desamparados' AND ID_PROVINCIA=1)),
('San Juan de Dios', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Desamparados' AND ID_PROVINCIA=1)),
('San Rafael Arriba', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Desamparados' AND ID_PROVINCIA=1)),
('San Antonio', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Desamparados' AND ID_PROVINCIA=1)),
('Frailes', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Desamparados' AND ID_PROVINCIA=1)),
('Patarrá', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Desamparados' AND ID_PROVINCIA=1)),
('San Cristóbal', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Desamparados' AND ID_PROVINCIA=1)),
('Rosario', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Desamparados' AND ID_PROVINCIA=1));

-- Puriscal
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Santiago', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puriscal' AND ID_PROVINCIA=1)),
('Mercedes Sur', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puriscal' AND ID_PROVINCIA=1)),
('Barbacoas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puriscal' AND ID_PROVINCIA=1)),
('Grifo Alto', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puriscal' AND ID_PROVINCIA=1));

-- Tarrazú
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Marcos', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tarrazú' AND ID_PROVINCIA=1)),
('San Lorenzo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tarrazú' AND ID_PROVINCIA=1)),
('San Carlos', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tarrazú' AND ID_PROVINCIA=1));

-- Aserrí
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Aserrí', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Aserrí' AND ID_PROVINCIA=1)),
('Turbaco', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Aserrí' AND ID_PROVINCIA=1)),
('Vuelta de Jorco', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Aserrí' AND ID_PROVINCIA=1)),
('San Gabriel', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Aserrí' AND ID_PROVINCIA=1)),
('Legua', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Aserrí' AND ID_PROVINCIA=1)),
('Monterrey', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Aserrí' AND ID_PROVINCIA=1));

-- Mora
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Colón', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Mora' AND ID_PROVINCIA=1)),
('Guayabo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Mora' AND ID_PROVINCIA=1)),
('Tabarcia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Mora' AND ID_PROVINCIA=1)),
('Piedras Negras', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Mora' AND ID_PROVINCIA=1)),
('Picagres', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Mora' AND ID_PROVINCIA=1));

-- Goicoechea
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Guadalupe', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Goicoechea' AND ID_PROVINCIA=1)),
('San Francisco', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Goicoechea' AND ID_PROVINCIA=1)),
('Calle Blancos', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Goicoechea' AND ID_PROVINCIA=1)),
('Mata de Plátano', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Goicoechea' AND ID_PROVINCIA=1));

-- Santa Ana
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Santa Ana', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Ana' AND ID_PROVINCIA=1)),
('Salitral', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Ana' AND ID_PROVINCIA=1)),
('Pozos', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Ana' AND ID_PROVINCIA=1)),
('Ulloa', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Ana' AND ID_PROVINCIA=1)),
('Piedades', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Ana' AND ID_PROVINCIA=1));

-- Alajuelita
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Alajuelita', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuelita' AND ID_PROVINCIA=1)),
('San Josecito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuelita' AND ID_PROVINCIA=1)),
('San Antonio', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuelita' AND ID_PROVINCIA=1)),
('Concepción', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuelita' AND ID_PROVINCIA=1));

-- Vázquez de Coronado
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Isidro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Vázquez de Coronado' AND ID_PROVINCIA=1)),
('San Rafael', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Vázquez de Coronado' AND ID_PROVINCIA=1)),
('Dulce Nombre de Jesús', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Vázquez de Coronado' AND ID_PROVINCIA=1)),
('Patalillo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Vázquez de Coronado' AND ID_PROVINCIA=1));

-- Acosta
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Ignacio', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Acosta' AND ID_PROVINCIA=1)),
('Guaitil', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Acosta' AND ID_PROVINCIA=1)),
('Palmichal', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Acosta' AND ID_PROVINCIA=1)),
('Cangrejal', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Acosta' AND ID_PROVINCIA=1)),
('Sabanillas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Acosta' AND ID_PROVINCIA=1));

-- Tibás
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Juan', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tibás' AND ID_PROVINCIA=1)),
('Cinco Esquinas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tibás' AND ID_PROVINCIA=1)),
('Anselmo Llorente', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tibás' AND ID_PROVINCIA=1)),
('León XIII', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tibás' AND ID_PROVINCIA=1));

-- Moravia
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Vicente', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Moravia' AND ID_PROVINCIA=1)),
('San Jerónimo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Moravia' AND ID_PROVINCIA=1)),
('La Trinidad', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Moravia' AND ID_PROVINCIA=1));

-- Montes de Oca
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Pedro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Montes de Oca' AND ID_PROVINCIA=1)),
('Sabanilla', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Montes de Oca' AND ID_PROVINCIA=1)),
('Mercedes', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Montes de Oca' AND ID_PROVINCIA=1));

-- Turrubares
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Pablo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrubares' AND ID_PROVINCIA=1)),
('San Pedro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrubares' AND ID_PROVINCIA=1)),
('San Juan de Mata', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrubares' AND ID_PROVINCIA=1)),
('San Luis', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrubares' AND ID_PROVINCIA=1));

-- Dota
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Santa María', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Dota' AND ID_PROVINCIA=1)),
('Jardín', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Dota' AND ID_PROVINCIA=1)),
('Copey', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Dota' AND ID_PROVINCIA=1));

-- Curridabat
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Curridabat', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Curridabat' AND ID_PROVINCIA=1)),
('Granadilla', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Curridabat' AND ID_PROVINCIA=1)),
('Sánchez', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Curridabat' AND ID_PROVINCIA=1)),
('Tirrases', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Curridabat' AND ID_PROVINCIA=1));

-- Pérez Zeledón
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Isidro de El General', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pérez Zeledón' AND ID_PROVINCIA=1)),
('General', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pérez Zeledón' AND ID_PROVINCIA=1)),
('Daniel Flores', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pérez Zeledón' AND ID_PROVINCIA=1)),
('Rivas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pérez Zeledón' AND ID_PROVINCIA=1)),
('Pejibaye', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pérez Zeledón' AND ID_PROVINCIA=1)),
('Páramo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pérez Zeledón' AND ID_PROVINCIA=1)),
('La Amistad', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pérez Zeledón' AND ID_PROVINCIA=1));

-- León Cortés Castro
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Pablo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='León Cortés Castro' AND ID_PROVINCIA=1)),
('San Andrés', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='León Cortés Castro' AND ID_PROVINCIA=1)),
('Llano Bonito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='León Cortés Castro' AND ID_PROVINCIA=1)),
('San Isidro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='León Cortés Castro' AND ID_PROVINCIA=1));


-- Cartago

INSERT INTO CANTON (DESCRIPCION, ACTIVO, ID_PROVINCIA) VALUES
('Cartago', 1, 2),
('Paraíso', 1, 2),
('La Unión', 1, 2),
('Jiménez', 1, 2),
('Turrialba', 1, 2),
('Alvarado', 1, 2),
('Oreamuno', 1, 2),
('El Guarco', 1, 2);

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Oriental', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2)),
('Occidental', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2)),
('Carmen', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2)),
('San Nicolás', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2)),
('Aguacaliente', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2)),
('Guadalupe', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2)),
('Corralillo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2)),
('Tierra Blanca', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2)),
('Dulce Nombre', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2)),
('Llano Grande', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2)),
('Quebradilla', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cartago' AND ID_PROVINCIA=2));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Paraíso', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Paraíso' AND ID_PROVINCIA=2)),
('Santiago', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Paraíso' AND ID_PROVINCIA=2)),
('Orosi', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Paraíso' AND ID_PROVINCIA=2)),
('Cachí', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Paraíso' AND ID_PROVINCIA=2)),
('Llanos de Santa Lucía', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Paraíso' AND ID_PROVINCIA=2)),
('Birrisito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Paraíso' AND ID_PROVINCIA=2));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Tres Ríos', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Unión' AND ID_PROVINCIA=2)),
('San Diego', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Unión' AND ID_PROVINCIA=2)),
('San Juan', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Unión' AND ID_PROVINCIA=2)),
('San Rafael', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Unión' AND ID_PROVINCIA=2)),
('Concepción', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Unión' AND ID_PROVINCIA=2)),
('Dulce Nombre', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Unión' AND ID_PROVINCIA=2)),
('San Ramón', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Unión' AND ID_PROVINCIA=2)),
('Río Azul', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Unión' AND ID_PROVINCIA=2));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Juan Viñas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Jiménez' AND ID_PROVINCIA=2)),
('Tucurrique', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Jiménez' AND ID_PROVINCIA=2)),
('Pejibaye', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Jiménez' AND ID_PROVINCIA=2)),
('La Victoria', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Jiménez' AND ID_PROVINCIA=2));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Turrialba', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('La Suiza', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('Peralta', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('Santa Cruz', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('Santa Teresita', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('Pavones', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('Tuis', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('Tayutic', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('Santa Rosa', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('Tres Equis', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('La Isabel', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2)),
('Chirripó', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Turrialba' AND ID_PROVINCIA=2));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Pacayas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alvarado' AND ID_PROVINCIA=2)),
('Cervantes', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alvarado' AND ID_PROVINCIA=2)),
('Capellades', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alvarado' AND ID_PROVINCIA=2));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Rafael', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Oreamuno' AND ID_PROVINCIA=2)),
('Cot', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Oreamuno' AND ID_PROVINCIA=2)),
('Potrero Cerrado', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Oreamuno' AND ID_PROVINCIA=2)),
('Cipreses', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Oreamuno' AND ID_PROVINCIA=2)),
('Santa Rosa', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Oreamuno' AND ID_PROVINCIA=2));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('El Tejar', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='El Guarco' AND ID_PROVINCIA=2)),
('San Isidro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='El Guarco' AND ID_PROVINCIA=2)),
('Tobosi', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='El Guarco' AND ID_PROVINCIA=2)),
('Patio de Agua', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='El Guarco' AND ID_PROVINCIA=2));


--Heredia

INSERT INTO CANTON (DESCRIPCION, ACTIVO, ID_PROVINCIA) VALUES
('Heredia', 1, 3),
('Barva', 1, 3),
('Santo Domingo', 1, 3),
('Santa Bárbara', 1, 3),
('San Rafael', 1, 3),
('San Isidro', 1, 3),
('Belén', 1, 3),
('Flores', 1, 3),
('San Pablo', 1, 3),
('Sarapiquí', 1, 3);

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Heredia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Heredia' AND ID_PROVINCIA=3)),
('Mercedes', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Heredia' AND ID_PROVINCIA=3)),
('San Francisco', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Heredia' AND ID_PROVINCIA=3)),
('Ulloa', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Heredia' AND ID_PROVINCIA=3)),
('Varablanca', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Heredia' AND ID_PROVINCIA=3));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Barva', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Barva' AND ID_PROVINCIA=3)),
('San Pedro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Barva' AND ID_PROVINCIA=3)),
('San Pablo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Barva' AND ID_PROVINCIA=3)),
('San Roque', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Barva' AND ID_PROVINCIA=3)),
('Santa Lucía', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Barva' AND ID_PROVINCIA=3)),
('San José de la Montaña', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Barva' AND ID_PROVINCIA=3)),
('Puente Salas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Barva' AND ID_PROVINCIA=3));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Santo Domingo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santo Domingo' AND ID_PROVINCIA=3)),
('San Vicente', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santo Domingo' AND ID_PROVINCIA=3)),
('San Miguel', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santo Domingo' AND ID_PROVINCIA=3)),
('Paracito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santo Domingo' AND ID_PROVINCIA=3)),
('Santo Tomás', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santo Domingo' AND ID_PROVINCIA=3)),
('Santa Rosa', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santo Domingo' AND ID_PROVINCIA=3)),
('Tures', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santo Domingo' AND ID_PROVINCIA=3)),
('Pará', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santo Domingo' AND ID_PROVINCIA=3));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Santa Bárbara', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Bárbara' AND ID_PROVINCIA=3)),
('San Pedro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Bárbara' AND ID_PROVINCIA=3)),
('San Juan', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Bárbara' AND ID_PROVINCIA=3)),
('Jesús', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Bárbara' AND ID_PROVINCIA=3)),
('Santo Domingo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Bárbara' AND ID_PROVINCIA=3)),
('Purabá', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Bárbara' AND ID_PROVINCIA=3));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Rafael', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Rafael' AND ID_PROVINCIA=3)),
('San Josecito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Rafael' AND ID_PROVINCIA=3)),
('Santiago', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Rafael' AND ID_PROVINCIA=3)),
('Ángeles', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Rafael' AND ID_PROVINCIA=3)),
('Concepción', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Rafael' AND ID_PROVINCIA=3));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Isidro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Isidro' AND ID_PROVINCIA=3)),
('San José', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Isidro' AND ID_PROVINCIA=3)),
('Concepción', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Isidro' AND ID_PROVINCIA=3)),
('San Francisco', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Isidro' AND ID_PROVINCIA=3));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Antonio', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Belén' AND ID_PROVINCIA=3)),
('La Ribera', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Belén' AND ID_PROVINCIA=3)),
('La Asunción', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Belén' AND ID_PROVINCIA=3));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Joaquín', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Flores' AND ID_PROVINCIA=3)),
('Barrantes', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Flores' AND ID_PROVINCIA=3)),
('Llorente', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Flores' AND ID_PROVINCIA=3));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Pablo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Pablo' AND ID_PROVINCIA=3)),
('Rincón de Sabanilla', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Pablo' AND ID_PROVINCIA=3));

INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Puerto Viejo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Sarapiquí' AND ID_PROVINCIA=3)),
('La Virgen', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Sarapiquí' AND ID_PROVINCIA=3)),
('Horquetas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Sarapiquí' AND ID_PROVINCIA=3)),
('Llanuras del Gaspar', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Sarapiquí' AND ID_PROVINCIA=3)),
('Cureña', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Sarapiquí' AND ID_PROVINCIA=3));




--Limon

INSERT INTO CANTON (DESCRIPCION, ACTIVO, ID_PROVINCIA) VALUES
('Limón', 1, 4),
('Pococí', 1, 4),
('Siquirres', 1, 4),
('Talamanca', 1, 4),
('Matina', 1, 4),
('Guácimo', 1, 4);

-- Cantón: Limón
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Limón', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Limón' AND ID_PROVINCIA=4)),
('Valle La Estrella', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Limón' AND ID_PROVINCIA=4)),
('Río Blanco', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Limón' AND ID_PROVINCIA=4)),
('Matama', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Limón' AND ID_PROVINCIA=4));

-- Cantón: Pococí
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Guápiles', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pococí' AND ID_PROVINCIA=4)),
('Jiménez', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pococí' AND ID_PROVINCIA=4)),
('La Rita', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pococí' AND ID_PROVINCIA=4)),
('Roxana', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pococí' AND ID_PROVINCIA=4)),
('Cariari', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pococí' AND ID_PROVINCIA=4)),
('Colorado', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pococí' AND ID_PROVINCIA=4)),
('La Colonia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Pococí' AND ID_PROVINCIA=4));

-- Cantón: Siquirres
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Siquirres', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Siquirres' AND ID_PROVINCIA=4)),
('Pacuarito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Siquirres' AND ID_PROVINCIA=4)),
('Florida', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Siquirres' AND ID_PROVINCIA=4)),
('Germania', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Siquirres' AND ID_PROVINCIA=4)),
('El Cairo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Siquirres' AND ID_PROVINCIA=4)),
('Alegría', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Siquirres' AND ID_PROVINCIA=4)),
('Reventazón', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Siquirres' AND ID_PROVINCIA=4));

-- Cantón: Talamanca
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Bratsi', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Talamanca' AND ID_PROVINCIA=4)),
('Sixaola', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Talamanca' AND ID_PROVINCIA=4)),
('Cahuita', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Talamanca' AND ID_PROVINCIA=4)),
('Telire', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Talamanca' AND ID_PROVINCIA=4));

-- Cantón: Matina
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Matina', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Matina' AND ID_PROVINCIA=4)),
('Batán', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Matina' AND ID_PROVINCIA=4)),
('Carrandi', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Matina' AND ID_PROVINCIA=4));

-- Cantón: Guácimo
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Guácimo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Guácimo' AND ID_PROVINCIA=4)),
('Mercedes', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Guácimo' AND ID_PROVINCIA=4)),
('Pocora', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Guácimo' AND ID_PROVINCIA=4)),
('Río Jiménez', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Guácimo' AND ID_PROVINCIA=4)),
('Duacarí', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Guácimo' AND ID_PROVINCIA=4));





--Guanacaste

INSERT INTO CANTON (DESCRIPCION, ACTIVO, ID_PROVINCIA) VALUES
('Liberia', 1, 5),
('Nicoya', 1, 5),
('Santa Cruz', 1, 5),
('Bagaces', 1, 5),
('Carrillo', 1, 5),
('Cañas', 1, 5),
('Abangares', 1, 5),
('Tilarán', 1, 5),
('Nandayure', 1, 5),
('La Cruz', 1, 5),
('Hojancha', 1, 5);


-- Cantón: Liberia
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Liberia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Liberia' AND ID_PROVINCIA=5)),
('Cañas Dulces', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Liberia' AND ID_PROVINCIA=5)),
('Mayorga', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Liberia' AND ID_PROVINCIA=5)),
('Nacascolo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Liberia' AND ID_PROVINCIA=5)),
('Curubandé', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Liberia' AND ID_PROVINCIA=5));

-- Cantón: Nicoya
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Nicoya', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nicoya' AND ID_PROVINCIA=5)),
('Mansión', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nicoya' AND ID_PROVINCIA=5)),
('San Antonio', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nicoya' AND ID_PROVINCIA=5)),
('Quebrada Honda', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nicoya' AND ID_PROVINCIA=5)),
('Sámara', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nicoya' AND ID_PROVINCIA=5)),
('Nosara', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nicoya' AND ID_PROVINCIA=5)),
('Belén de Nosarita', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nicoya' AND ID_PROVINCIA=5));

-- Cantón: Santa Cruz
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Santa Cruz', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Cruz' AND ID_PROVINCIA=5)),
('Bolsón', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Cruz' AND ID_PROVINCIA=5)),
('Veintisiete de Abril', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Cruz' AND ID_PROVINCIA=5)),
('Tempate', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Cruz' AND ID_PROVINCIA=5)),
('Cartagena', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Cruz' AND ID_PROVINCIA=5)),
('Cuajiniquil', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Cruz' AND ID_PROVINCIA=5)),
('Diriá', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Cruz' AND ID_PROVINCIA=5)),
('Cabo Velas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Cruz' AND ID_PROVINCIA=5)),
('Tamarindo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Santa Cruz' AND ID_PROVINCIA=5));

-- Cantón: Bagaces
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Bagaces', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Bagaces' AND ID_PROVINCIA=5)),
('La Fortuna', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Bagaces' AND ID_PROVINCIA=5)),
('Mogote', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Bagaces' AND ID_PROVINCIA=5)),
('Río Naranjo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Bagaces' AND ID_PROVINCIA=5));

-- Cantón: Carrillo
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Filadelfia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Carrillo' AND ID_PROVINCIA=5)),
('Palmira', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Carrillo' AND ID_PROVINCIA=5)),
('Sardinal', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Carrillo' AND ID_PROVINCIA=5)),
('Belén', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Carrillo' AND ID_PROVINCIA=5));

-- Cantón: Cañas
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Cañas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cañas' AND ID_PROVINCIA=5)),
('Palmira', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cañas' AND ID_PROVINCIA=5)),
('San Miguel', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cañas' AND ID_PROVINCIA=5)),
('Bebedero', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cañas' AND ID_PROVINCIA=5)),
('Porozal', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Cañas' AND ID_PROVINCIA=5));

-- Cantón: Abangares
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Las Juntas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Abangares' AND ID_PROVINCIA=5)),
('Sierra', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Abangares' AND ID_PROVINCIA=5)),
('San Juan', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Abangares' AND ID_PROVINCIA=5)),
('Colorado', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Abangares' AND ID_PROVINCIA=5));

-- Cantón: Tilarán
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Tilarán', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tilarán' AND ID_PROVINCIA=5)),
('Quebrada Grande', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tilarán' AND ID_PROVINCIA=5)),
('Tronadora', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tilarán' AND ID_PROVINCIA=5)),
('Santa Rosa', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tilarán' AND ID_PROVINCIA=5)),
('Líbano', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tilarán' AND ID_PROVINCIA=5)),
('Tierras Morenas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tilarán' AND ID_PROVINCIA=5)),
('Arenal', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tilarán' AND ID_PROVINCIA=5)),
('Cabeceras', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Tilarán' AND ID_PROVINCIA=5));

-- Cantón: Nandayure
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Carmona', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nandayure' AND ID_PROVINCIA=5)),
('Santa Rita', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nandayure' AND ID_PROVINCIA=5)),
('San Pablo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nandayure' AND ID_PROVINCIA=5)),
('San Pedro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nandayure' AND ID_PROVINCIA=5)),
('Bejuco', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Nandayure' AND ID_PROVINCIA=5));

-- Cantón: La Cruz
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('La Cruz', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Cruz' AND ID_PROVINCIA=5)),
('Santa Cecilia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Cruz' AND ID_PROVINCIA=5)),
('Lobos', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Cruz' AND ID_PROVINCIA=5)),
('Cacao', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='La Cruz' AND ID_PROVINCIA=5));

-- Cantón: Hojancha
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Hojancha', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Hojancha' AND ID_PROVINCIA=5)),
('Puerto Carrillo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Hojancha' AND ID_PROVINCIA=5)),
('Matambú', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Hojancha' AND ID_PROVINCIA=5)),
('Los Ángeles', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Hojancha' AND ID_PROVINCIA=5));





--Puntarenas

INSERT INTO CANTON (DESCRIPCION, ACTIVO, ID_PROVINCIA) VALUES
('Puntarenas', 1, 6),
('Esparza', 1, 6),
('Buenos Aires', 1, 6),
('Montes de Oro', 1, 6),
('Osa', 1, 6),
('Quepos', 1, 6),
('Golfito', 1, 6),
('Coto Brus', 1, 6),
('Parrita', 1, 6),
('Corredores', 1, 6),
('Garabito', 1, 6);

-- Inserta distritos para cada cantón (usando SELECT ID_CANTON)

-- Cantón: Puntarenas
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Puntarenas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Pitahaya', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Chomes', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Lepanto', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Paquera', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Manzanillo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Guácimal', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Barranca', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Isla del Coco', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Cóbano', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Chacarita', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Chira', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Acapulco', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('El Roble', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6)),
('Arancibia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Puntarenas' AND ID_PROVINCIA=6));

-- Cantón: Esparza
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Espíritu Santo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Esparza' AND ID_PROVINCIA=6)),
('San Juan Grande', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Esparza' AND ID_PROVINCIA=6)),
('Macacona', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Esparza' AND ID_PROVINCIA=6)),
('San Rafael', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Esparza' AND ID_PROVINCIA=6)),
('San Jerónimo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Esparza' AND ID_PROVINCIA=6)),
('Caldera', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Esparza' AND ID_PROVINCIA=6));

-- Cantón: Buenos Aires
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Buenos Aires', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Buenos Aires' AND ID_PROVINCIA=6)),
('Volcán', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Buenos Aires' AND ID_PROVINCIA=6)),
('Potrero Grande', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Buenos Aires' AND ID_PROVINCIA=6)),
('Boruca', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Buenos Aires' AND ID_PROVINCIA=6)),
('Pilas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Buenos Aires' AND ID_PROVINCIA=6)),
('Colinas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Buenos Aires' AND ID_PROVINCIA=6)),
('Chánguena', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Buenos Aires' AND ID_PROVINCIA=6)),
('Biolley', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Buenos Aires' AND ID_PROVINCIA=6)),
('Brunka', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Buenos Aires' AND ID_PROVINCIA=6));

-- Cantón: Montes de Oro
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Miramar', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Montes de Oro' AND ID_PROVINCIA=6)),
('La Unión', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Montes de Oro' AND ID_PROVINCIA=6)),
('San Isidro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Montes de Oro' AND ID_PROVINCIA=6));

-- Cantón: Osa
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Puerto Cortés', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Osa' AND ID_PROVINCIA=6)),
('Palmar', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Osa' AND ID_PROVINCIA=6)),
('Sierpe', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Osa' AND ID_PROVINCIA=6)),
('Bahía Ballena', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Osa' AND ID_PROVINCIA=6)),
('Piedras Blancas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Osa' AND ID_PROVINCIA=6)),
('Bahía Drake', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Osa' AND ID_PROVINCIA=6));

-- Cantón: Quepos
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Quepos', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Quepos' AND ID_PROVINCIA=6)),
('Savegre', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Quepos' AND ID_PROVINCIA=6)),
('Naranjito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Quepos' AND ID_PROVINCIA=6));

-- Cantón: Golfito
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Golfito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Golfito' AND ID_PROVINCIA=6)),
('Guaycará', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Golfito' AND ID_PROVINCIA=6)),
('Pavón', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Golfito' AND ID_PROVINCIA=6));

-- Cantón: Coto Brus
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Vito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Coto Brus' AND ID_PROVINCIA=6)),
('Sabalito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Coto Brus' AND ID_PROVINCIA=6)),
('Aguabuena', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Coto Brus' AND ID_PROVINCIA=6)),
('Limoncito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Coto Brus' AND ID_PROVINCIA=6)),
('Pittier', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Coto Brus' AND ID_PROVINCIA=6)),
('Gutiérrez Braun', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Coto Brus' AND ID_PROVINCIA=6));

-- Cantón: Parrita
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Parrita', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Parrita' AND ID_PROVINCIA=6));

-- Cantón: Corredores
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Corredor', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Corredores' AND ID_PROVINCIA=6)),
('La Cuesta', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Corredores' AND ID_PROVINCIA=6)),
('Canoas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Corredores' AND ID_PROVINCIA=6)),
('Laurel', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Corredores' AND ID_PROVINCIA=6)),
('La Cuesta', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Corredores' AND ID_PROVINCIA=6));

-- Cantón: Garabito
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Jacó', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Garabito' AND ID_PROVINCIA=6)),
('Tárcoles', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Garabito' AND ID_PROVINCIA=6));




--Alajuela

INSERT INTO CANTON (DESCRIPCION, ACTIVO, ID_PROVINCIA) VALUES
('Alajuela', 1, 7),
('San Ramón', 1, 7),
('Grecia', 1, 7),
('San Mateo', 1, 7),
('Atenas', 1, 7),
('Naranjo', 1, 7),
('Palmares', 1, 7),
('Poás', 1, 7),
('Orotina', 1, 7),
('San Carlos', 1, 7),
('Zarcero', 1, 7),
('Sarchí', 1, 7),
('Upala', 1, 7),
('Los Chiles', 1, 7),
('Guatuso', 1, 7);

-- Inserta distritos para cada cantón (usando SELECT ID_CANTON)

-- Cantón: Alajuela
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Alajuela', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('San José', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('Carrizal', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('San Antonio', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('Guácima', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('San Isidro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('Sabanilla', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('San Rafael', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('Río Segundo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('Desamparados', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('Turrúcares', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('Tambor', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('La Garita', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7)),
('Sarapiquí', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Alajuela' AND ID_PROVINCIA=7));

-- Cantón: San Ramón
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Ramón', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('Santiago', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('San Juan', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('Piedades Norte', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('Piedades Sur', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('San Rafael', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('San Isidro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('Ángeles', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('Alfaro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('Volio', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('Concepción', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('Zapotal', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('Peñas Blancas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7)),
('San Lorenzo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Ramón' AND ID_PROVINCIA=7));

-- Cantón: Grecia
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Grecia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Grecia' AND ID_PROVINCIA=7)),
('San Isidro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Grecia' AND ID_PROVINCIA=7)),
('San José', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Grecia' AND ID_PROVINCIA=7)),
('San Roque', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Grecia' AND ID_PROVINCIA=7)),
('Tacares', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Grecia' AND ID_PROVINCIA=7)),
('Puente de Piedra', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Grecia' AND ID_PROVINCIA=7)),
('Bolívar', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Grecia' AND ID_PROVINCIA=7));

-- Cantón: San Mateo
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Mateo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Mateo' AND ID_PROVINCIA=7)),
('Desmonte', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Mateo' AND ID_PROVINCIA=7)),
('Jesús María', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Mateo' AND ID_PROVINCIA=7)),
('Labrador', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Mateo' AND ID_PROVINCIA=7));

-- Cantón: Atenas
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Atenas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Atenas' AND ID_PROVINCIA=7)),
('Jesús', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Atenas' AND ID_PROVINCIA=7)),
('Mercedes', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Atenas' AND ID_PROVINCIA=7)),
('San Isidro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Atenas' AND ID_PROVINCIA=7)),
('Concepción', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Atenas' AND ID_PROVINCIA=7)),
('San José', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Atenas' AND ID_PROVINCIA=7)),
('Santa Eulalia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Atenas' AND ID_PROVINCIA=7)),
('Escobal', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Atenas' AND ID_PROVINCIA=7));

-- Cantón: Naranjo
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Naranjo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Naranjo' AND ID_PROVINCIA=7)),
('San Miguel', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Naranjo' AND ID_PROVINCIA=7)),
('San José', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Naranjo' AND ID_PROVINCIA=7)),
('Cirrí Sur', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Naranjo' AND ID_PROVINCIA=7)),
('San Jerónimo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Naranjo' AND ID_PROVINCIA=7)),
('San Juan', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Naranjo' AND ID_PROVINCIA=7));

-- Cantón: Palmares
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Palmares', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Palmares' AND ID_PROVINCIA=7)),
('Zaragoza', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Palmares' AND ID_PROVINCIA=7)),
('Buenos Aires', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Palmares' AND ID_PROVINCIA=7)),
('Santiago', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Palmares' AND ID_PROVINCIA=7)),
('Candelaria', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Palmares' AND ID_PROVINCIA=7)),
('Esquipulas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Palmares' AND ID_PROVINCIA=7));

-- Cantón: Poás
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Pedro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Poás' AND ID_PROVINCIA=7)),
('San Juan', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Poás' AND ID_PROVINCIA=7)),
('San Rafael', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Poás' AND ID_PROVINCIA=7)),
('Carrillos', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Poás' AND ID_PROVINCIA=7)),
('Sabana Redonda', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Poás' AND ID_PROVINCIA=7));

-- Cantón: Orotina
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Orotina', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Orotina' AND ID_PROVINCIA=7)),
('El Mastate', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Orotina' AND ID_PROVINCIA=7)),
('Hacienda Vieja', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Orotina' AND ID_PROVINCIA=7)),
('Calle Blancos', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Orotina' AND ID_PROVINCIA=7)),
('Coyolar', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Orotina' AND ID_PROVINCIA=7)),
('Ceiba', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Orotina' AND ID_PROVINCIA=7));

-- Cantón: San Carlos
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Quesada', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7)),
('Florencia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7)),
('Buenavista', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7)),
('Aguas Zarcas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7)),
('Venecia', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7)),
('Pital', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7)),
('La Fortuna', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7)),
('La Tigra', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7)),
('El Tanque', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7)),
('Venado', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7)),
('Pocosol', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='San Carlos' AND ID_PROVINCIA=7));

-- Cantón: Zarcero
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Zarcero', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Zarcero' AND ID_PROVINCIA=7)),
('Lagunas', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Zarcero' AND ID_PROVINCIA=7)),
('Tapezco', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Zarcero' AND ID_PROVINCIA=7)),
('Guayabito', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Zarcero' AND ID_PROVINCIA=7)),
('Palmira', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Zarcero' AND ID_PROVINCIA=7));

-- Cantón: Sarchí
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Sarchí Norte', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Sarchí' AND ID_PROVINCIA=7)),
('Sarchí Sur', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Sarchí' AND ID_PROVINCIA=7)),
('Toro Amarillo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Sarchí' AND ID_PROVINCIA=7)),
('San Pedro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Sarchí' AND ID_PROVINCIA=7)),
('Rodríguez', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Sarchí' AND ID_PROVINCIA=7));

-- Cantón: Upala
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Upala', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Upala' AND ID_PROVINCIA=7)),
('Aguas Claras', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Upala' AND ID_PROVINCIA=7)),
('San José (Upala)', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Upala' AND ID_PROVINCIA=7)),
('Bijagua', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Upala' AND ID_PROVINCIA=7)),
('Delicias', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Upala' AND ID_PROVINCIA=7)),
('Dos Ríos', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Upala' AND ID_PROVINCIA=7));

-- Cantón: Los Chiles
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('Los Chiles', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Los Chiles' AND ID_PROVINCIA=7)),
('Caño Negro', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Los Chiles' AND ID_PROVINCIA=7)),
('El Amparo', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Los Chiles' AND ID_PROVINCIA=7)),
('San Jorge', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Los Chiles' AND ID_PROVINCIA=7));

-- Cantón: Guatuso
INSERT INTO DISTRITO (DESCRIPCION, ACTIVO, ID_CANTON) VALUES
('San Rafael', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Guatuso' AND ID_PROVINCIA=7)),
('Buenavista', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Guatuso' AND ID_PROVINCIA=7)),
('Cote', 1, (SELECT ID_CANTON FROM CANTON WHERE DESCRIPCION='Guatuso' AND ID_PROVINCIA=7));
